module.exports={
    configureWebpack:{
        resolve:{
            alias:{
                'assets':'src/assets',
                'common':'src/common',
                'components':'src/components',
                'views':'src/views',
                'store':'src/store',
                'router':'src/router'
            }
        }
    }
}
